/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STUDENCI_H_RPCGEN
#define _STUDENCI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


enum Ocena {
	NDST = 0,
	DST = 1,
	DST_P = 2,
	DB = 3,
	DB_P = 4,
	BDB = 5,
};
typedef enum Ocena Ocena;

enum TypIdentyfikatora {
	NUMER_ALBUMU = 1,
	ADRES_EMAIL = 2,
};
typedef enum TypIdentyfikatora TypIdentyfikatora;

struct IdentyfikatorStudenta {
	TypIdentyfikatora typ;
	union {
		u_int numer_albumu;
		char *email;
	} IdentyfikatorStudenta_u;
};
typedef struct IdentyfikatorStudenta IdentyfikatorStudenta;

struct Student {
	IdentyfikatorStudenta identyfikator;
	char *nazwisko;
	char *imie;
	struct {
		u_int oceny_len;
		Ocena *oceny_val;
	} oceny;
};
typedef struct Student Student;

typedef struct {
	u_int ListaStudentow_len;
	Student *ListaStudentow_val;
} ListaStudentow;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Ocena (XDR *, Ocena*);
extern  bool_t xdr_TypIdentyfikatora (XDR *, TypIdentyfikatora*);
extern  bool_t xdr_IdentyfikatorStudenta (XDR *, IdentyfikatorStudenta*);
extern  bool_t xdr_Student (XDR *, Student*);
extern  bool_t xdr_ListaStudentow (XDR *, ListaStudentow*);

#else /* K&R C */
extern bool_t xdr_Ocena ();
extern bool_t xdr_TypIdentyfikatora ();
extern bool_t xdr_IdentyfikatorStudenta ();
extern bool_t xdr_Student ();
extern bool_t xdr_ListaStudentow ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STUDENCI_H_RPCGEN */
