/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "studenci.h"

bool_t
xdr_Ocena (XDR *xdrs, Ocena *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TypIdentyfikatora (XDR *xdrs, TypIdentyfikatora *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_IdentyfikatorStudenta (XDR *xdrs, IdentyfikatorStudenta *objp)
{
	register int32_t *buf;

	 if (!xdr_TypIdentyfikatora (xdrs, &objp->typ))
		 return FALSE;
	switch (objp->typ) {
	case NUMER_ALBUMU:
		 if (!xdr_u_int (xdrs, &objp->IdentyfikatorStudenta_u.numer_albumu))
			 return FALSE;
		break;
	case ADRES_EMAIL:
		 if (!xdr_string (xdrs, &objp->IdentyfikatorStudenta_u.email, ~0))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_Student (XDR *xdrs, Student *objp)
{
	register int32_t *buf;

	 if (!xdr_IdentyfikatorStudenta (xdrs, &objp->identyfikator))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nazwisko, 20))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->imie, 20))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->oceny.oceny_val, (u_int *) &objp->oceny.oceny_len, ~0,
		sizeof (Ocena), (xdrproc_t) xdr_Ocena))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ListaStudentow (XDR *xdrs, ListaStudentow *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->ListaStudentow_val, (u_int *) &objp->ListaStudentow_len, ~0,
		sizeof (Student), (xdrproc_t) xdr_Student))
		 return FALSE;
	return TRUE;
}
