# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: student.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstudent.proto\x12\x0cstudent_data\"\x84\x01\n\x07Student\x12\x13\n\tnr_albumu\x18\x01 \x01(\rH\x00\x12\x0f\n\x05\x65mail\x18\x02 \x01(\tH\x00\x12\x10\n\x08nazwisko\x18\x03 \x01(\t\x12\x0c\n\x04imie\x18\x04 \x01(\t\x12\"\n\x05oceny\x18\x05 \x03(\x0e\x32\x13.student_data.GradeB\x0f\n\ridentyfikator\"7\n\x0cStudentsList\x12\'\n\x08studenci\x18\x01 \x03(\x0b\x32\x15.student_data.Student*@\n\x05Grade\x12\x08\n\x04NDST\x10\x00\x12\x07\n\x03\x44ST\x10\x01\x12\t\n\x05\x44ST_P\x10\x02\x12\x06\n\x02\x44\x42\x10\x03\x12\x08\n\x04\x44\x42_P\x10\x04\x12\x07\n\x03\x42\x44\x42\x10\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'student_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GRADE._serialized_start=223
  _GRADE._serialized_end=287
  _STUDENT._serialized_start=32
  _STUDENT._serialized_end=164
  _STUDENTSLIST._serialized_start=166
  _STUDENTSLIST._serialized_end=221
# @@protoc_insertion_point(module_scope)
