/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LICZNIK_H_RPCGEN
#define _LICZNIK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define LICZNIK 0x20123456
#define V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define zwieksz 1
extern  int * zwieksz_1(int *, CLIENT *);
extern  int * zwieksz_1_svc(int *, struct svc_req *);
#define zmniejsz 2
extern  int * zmniejsz_1(int *, CLIENT *);
extern  int * zmniejsz_1_svc(int *, struct svc_req *);
extern int licznik_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define zwieksz 1
extern  int * zwieksz_1();
extern  int * zwieksz_1_svc();
#define zmniejsz 2
extern  int * zmniejsz_1();
extern  int * zmniejsz_1_svc();
extern int licznik_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LICZNIK_H_RPCGEN */
