/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "licznik.h"

int *
zwieksz_1_svc(int *argp, struct svc_req *rqstp)
{
	static int result;

	printf("Otrzymano żądanie: zwieksz o %d\n", *argp);
	
	licznik_val = licznik_val + *argp; // Zwiększamy wartość licznika
	result = licznik_val;             // Przypisujemy nową wartość do wyniku

	printf("Aktualna wartość licznika: %d\n", result);

	return &result;
}

int *
zmniejsz_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Otrzymano żądanie: zmniejsz o %d\n", *argp);
	
	licznik_val = licznik_val - *argp; // Zmniejszamy wartość licznika
	result = licznik_val;             // Przypisujemy nową wartość do wyniku

	printf("Aktualna wartość licznika: %d\n", result);

	return &result;
}
