/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "licznik.h"


void
licznik_1(char *host, int wartosc)
{
	CLIENT *clnt;
	int  *result;


	clnt = clnt_create (host, LICZNIK, V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}


	if (wartosc >= 0){
		result = zwieksz_1(&wartosc, clnt);
	}
	else{
		int wartosc_dodatnia = -wartosc;
		result = zmniejsz_1(&wartosc_dodatnia, clnt);
	}

	if (result == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("Licznik: %d\n", *result);
	}

	clnt_destroy (clnt);

}


int
main (int argc, char *argv[])
{
	char *host;
	int wartosc;

	if (argc < 3) {
		printf ("inaczej uzyj", argv[0]);
		exit (1);
	}
	host = argv[1];
	wartosc = atoi(argv[2]);
	licznik_1 (host, wartosc);

	return 0;
exit (0);
}
