// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: licznik.proto

#include "licznik.pb.h"
#include "licznik.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* Licznik_method_names[] = {
  "/Licznik/zwieksz",
  "/Licznik/zmniejsz",
};

std::unique_ptr< Licznik::Stub> Licznik::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Licznik::Stub> stub(new Licznik::Stub(channel, options));
  return stub;
}

Licznik::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_zwieksz_(Licznik_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_zmniejsz_(Licznik_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Licznik::Stub::zwieksz(::grpc::ClientContext* context, const ::Wartosc& request, ::Wartosc* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Wartosc, ::Wartosc, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_zwieksz_, context, request, response);
}

void Licznik::Stub::async::zwieksz(::grpc::ClientContext* context, const ::Wartosc* request, ::Wartosc* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Wartosc, ::Wartosc, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_zwieksz_, context, request, response, std::move(f));
}

void Licznik::Stub::async::zwieksz(::grpc::ClientContext* context, const ::Wartosc* request, ::Wartosc* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_zwieksz_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Wartosc>* Licznik::Stub::PrepareAsynczwiekszRaw(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Wartosc, ::Wartosc, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_zwieksz_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Wartosc>* Licznik::Stub::AsynczwiekszRaw(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynczwiekszRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Licznik::Stub::zmniejsz(::grpc::ClientContext* context, const ::Wartosc& request, ::Wartosc* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Wartosc, ::Wartosc, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_zmniejsz_, context, request, response);
}

void Licznik::Stub::async::zmniejsz(::grpc::ClientContext* context, const ::Wartosc* request, ::Wartosc* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Wartosc, ::Wartosc, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_zmniejsz_, context, request, response, std::move(f));
}

void Licznik::Stub::async::zmniejsz(::grpc::ClientContext* context, const ::Wartosc* request, ::Wartosc* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_zmniejsz_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Wartosc>* Licznik::Stub::PrepareAsynczmniejszRaw(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Wartosc, ::Wartosc, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_zmniejsz_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Wartosc>* Licznik::Stub::AsynczmniejszRaw(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynczmniejszRaw(context, request, cq);
  result->StartCall();
  return result;
}

Licznik::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Licznik_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Licznik::Service, ::Wartosc, ::Wartosc, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Licznik::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Wartosc* req,
             ::Wartosc* resp) {
               return service->zwieksz(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Licznik_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Licznik::Service, ::Wartosc, ::Wartosc, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Licznik::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Wartosc* req,
             ::Wartosc* resp) {
               return service->zmniejsz(ctx, req, resp);
             }, this)));
}

Licznik::Service::~Service() {
}

::grpc::Status Licznik::Service::zwieksz(::grpc::ServerContext* context, const ::Wartosc* request, ::Wartosc* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Licznik::Service::zmniejsz(::grpc::ServerContext* context, const ::Wartosc* request, ::Wartosc* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


