// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: licznik.proto

#include "licznik.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR Wartosc::Wartosc(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.wartosc_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct WartoscDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WartoscDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WartoscDefaultTypeInternal() {}
  union {
    Wartosc _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WartoscDefaultTypeInternal _Wartosc_default_instance_;
static ::_pb::Metadata file_level_metadata_licznik_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_licznik_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_licznik_2eproto = nullptr;

const uint32_t TableStruct_licznik_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Wartosc, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Wartosc, _impl_.wartosc_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Wartosc)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_Wartosc_default_instance_._instance,
};

const char descriptor_table_protodef_licznik_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rlicznik.proto\"\032\n\007Wartosc\022\017\n\007wartosc\030\001 "
  "\001(\0052H\n\007Licznik\022\035\n\007zwieksz\022\010.Wartosc\032\010.Wa"
  "rtosc\022\036\n\010zmniejsz\022\010.Wartosc\032\010.Wartoscb\006p"
  "roto3"
  ;
static ::_pbi::once_flag descriptor_table_licznik_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_licznik_2eproto = {
    false, false, 125, descriptor_table_protodef_licznik_2eproto,
    "licznik.proto",
    &descriptor_table_licznik_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_licznik_2eproto::offsets,
    file_level_metadata_licznik_2eproto, file_level_enum_descriptors_licznik_2eproto,
    file_level_service_descriptors_licznik_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_licznik_2eproto_getter() {
  return &descriptor_table_licznik_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_licznik_2eproto(&descriptor_table_licznik_2eproto);

// ===================================================================

class Wartosc::_Internal {
 public:
};

Wartosc::Wartosc(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Wartosc)
}
Wartosc::Wartosc(const Wartosc& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Wartosc* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.wartosc_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.wartosc_ = from._impl_.wartosc_;
  // @@protoc_insertion_point(copy_constructor:Wartosc)
}

inline void Wartosc::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.wartosc_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Wartosc::~Wartosc() {
  // @@protoc_insertion_point(destructor:Wartosc)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Wartosc::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Wartosc::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Wartosc::Clear() {
// @@protoc_insertion_point(message_clear_start:Wartosc)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.wartosc_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Wartosc::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 wartosc = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.wartosc_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Wartosc::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Wartosc)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 wartosc = 1;
  if (this->_internal_wartosc() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_wartosc(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Wartosc)
  return target;
}

size_t Wartosc::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Wartosc)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 wartosc = 1;
  if (this->_internal_wartosc() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_wartosc());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Wartosc::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Wartosc::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Wartosc::GetClassData() const { return &_class_data_; }


void Wartosc::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Wartosc*>(&to_msg);
  auto& from = static_cast<const Wartosc&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Wartosc)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_wartosc() != 0) {
    _this->_internal_set_wartosc(from._internal_wartosc());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Wartosc::CopyFrom(const Wartosc& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Wartosc)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Wartosc::IsInitialized() const {
  return true;
}

void Wartosc::InternalSwap(Wartosc* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.wartosc_, other->_impl_.wartosc_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Wartosc::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_licznik_2eproto_getter, &descriptor_table_licznik_2eproto_once,
      file_level_metadata_licznik_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Wartosc*
Arena::CreateMaybeMessage< ::Wartosc >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Wartosc >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
