// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: licznik.proto
// Original file comments:
// licznik.proto - Definicja interfejsu gRPC dla zdalnego licznika
//
#ifndef GRPC_licznik_2eproto__INCLUDED
#define GRPC_licznik_2eproto__INCLUDED

#include "licznik.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

class Licznik final {
 public:
  static constexpr char const* service_full_name() {
    return "Licznik";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status zwieksz(::grpc::ClientContext* context, const ::Wartosc& request, ::Wartosc* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Wartosc>> Asynczwieksz(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Wartosc>>(AsynczwiekszRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Wartosc>> PrepareAsynczwieksz(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Wartosc>>(PrepareAsynczwiekszRaw(context, request, cq));
    }
    virtual ::grpc::Status zmniejsz(::grpc::ClientContext* context, const ::Wartosc& request, ::Wartosc* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Wartosc>> Asynczmniejsz(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Wartosc>>(AsynczmniejszRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Wartosc>> PrepareAsynczmniejsz(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Wartosc>>(PrepareAsynczmniejszRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void zwieksz(::grpc::ClientContext* context, const ::Wartosc* request, ::Wartosc* response, std::function<void(::grpc::Status)>) = 0;
      virtual void zwieksz(::grpc::ClientContext* context, const ::Wartosc* request, ::Wartosc* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void zmniejsz(::grpc::ClientContext* context, const ::Wartosc* request, ::Wartosc* response, std::function<void(::grpc::Status)>) = 0;
      virtual void zmniejsz(::grpc::ClientContext* context, const ::Wartosc* request, ::Wartosc* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Wartosc>* AsynczwiekszRaw(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Wartosc>* PrepareAsynczwiekszRaw(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Wartosc>* AsynczmniejszRaw(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Wartosc>* PrepareAsynczmniejszRaw(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status zwieksz(::grpc::ClientContext* context, const ::Wartosc& request, ::Wartosc* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Wartosc>> Asynczwieksz(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Wartosc>>(AsynczwiekszRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Wartosc>> PrepareAsynczwieksz(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Wartosc>>(PrepareAsynczwiekszRaw(context, request, cq));
    }
    ::grpc::Status zmniejsz(::grpc::ClientContext* context, const ::Wartosc& request, ::Wartosc* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Wartosc>> Asynczmniejsz(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Wartosc>>(AsynczmniejszRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Wartosc>> PrepareAsynczmniejsz(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Wartosc>>(PrepareAsynczmniejszRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void zwieksz(::grpc::ClientContext* context, const ::Wartosc* request, ::Wartosc* response, std::function<void(::grpc::Status)>) override;
      void zwieksz(::grpc::ClientContext* context, const ::Wartosc* request, ::Wartosc* response, ::grpc::ClientUnaryReactor* reactor) override;
      void zmniejsz(::grpc::ClientContext* context, const ::Wartosc* request, ::Wartosc* response, std::function<void(::grpc::Status)>) override;
      void zmniejsz(::grpc::ClientContext* context, const ::Wartosc* request, ::Wartosc* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Wartosc>* AsynczwiekszRaw(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Wartosc>* PrepareAsynczwiekszRaw(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Wartosc>* AsynczmniejszRaw(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Wartosc>* PrepareAsynczmniejszRaw(::grpc::ClientContext* context, const ::Wartosc& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_zwieksz_;
    const ::grpc::internal::RpcMethod rpcmethod_zmniejsz_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status zwieksz(::grpc::ServerContext* context, const ::Wartosc* request, ::Wartosc* response);
    virtual ::grpc::Status zmniejsz(::grpc::ServerContext* context, const ::Wartosc* request, ::Wartosc* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_zwieksz : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_zwieksz() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_zwieksz() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status zwieksz(::grpc::ServerContext* /*context*/, const ::Wartosc* /*request*/, ::Wartosc* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestzwieksz(::grpc::ServerContext* context, ::Wartosc* request, ::grpc::ServerAsyncResponseWriter< ::Wartosc>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_zmniejsz : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_zmniejsz() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_zmniejsz() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status zmniejsz(::grpc::ServerContext* /*context*/, const ::Wartosc* /*request*/, ::Wartosc* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestzmniejsz(::grpc::ServerContext* context, ::Wartosc* request, ::grpc::ServerAsyncResponseWriter< ::Wartosc>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_zwieksz<WithAsyncMethod_zmniejsz<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_zwieksz : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_zwieksz() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Wartosc, ::Wartosc>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Wartosc* request, ::Wartosc* response) { return this->zwieksz(context, request, response); }));}
    void SetMessageAllocatorFor_zwieksz(
        ::grpc::MessageAllocator< ::Wartosc, ::Wartosc>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Wartosc, ::Wartosc>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_zwieksz() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status zwieksz(::grpc::ServerContext* /*context*/, const ::Wartosc* /*request*/, ::Wartosc* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* zwieksz(
      ::grpc::CallbackServerContext* /*context*/, const ::Wartosc* /*request*/, ::Wartosc* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_zmniejsz : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_zmniejsz() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::Wartosc, ::Wartosc>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Wartosc* request, ::Wartosc* response) { return this->zmniejsz(context, request, response); }));}
    void SetMessageAllocatorFor_zmniejsz(
        ::grpc::MessageAllocator< ::Wartosc, ::Wartosc>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Wartosc, ::Wartosc>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_zmniejsz() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status zmniejsz(::grpc::ServerContext* /*context*/, const ::Wartosc* /*request*/, ::Wartosc* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* zmniejsz(
      ::grpc::CallbackServerContext* /*context*/, const ::Wartosc* /*request*/, ::Wartosc* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_zwieksz<WithCallbackMethod_zmniejsz<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_zwieksz : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_zwieksz() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_zwieksz() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status zwieksz(::grpc::ServerContext* /*context*/, const ::Wartosc* /*request*/, ::Wartosc* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_zmniejsz : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_zmniejsz() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_zmniejsz() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status zmniejsz(::grpc::ServerContext* /*context*/, const ::Wartosc* /*request*/, ::Wartosc* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_zwieksz : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_zwieksz() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_zwieksz() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status zwieksz(::grpc::ServerContext* /*context*/, const ::Wartosc* /*request*/, ::Wartosc* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestzwieksz(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_zmniejsz : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_zmniejsz() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_zmniejsz() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status zmniejsz(::grpc::ServerContext* /*context*/, const ::Wartosc* /*request*/, ::Wartosc* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestzmniejsz(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_zwieksz : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_zwieksz() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->zwieksz(context, request, response); }));
    }
    ~WithRawCallbackMethod_zwieksz() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status zwieksz(::grpc::ServerContext* /*context*/, const ::Wartosc* /*request*/, ::Wartosc* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* zwieksz(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_zmniejsz : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_zmniejsz() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->zmniejsz(context, request, response); }));
    }
    ~WithRawCallbackMethod_zmniejsz() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status zmniejsz(::grpc::ServerContext* /*context*/, const ::Wartosc* /*request*/, ::Wartosc* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* zmniejsz(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_zwieksz : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_zwieksz() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Wartosc, ::Wartosc>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Wartosc, ::Wartosc>* streamer) {
                       return this->Streamedzwieksz(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_zwieksz() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status zwieksz(::grpc::ServerContext* /*context*/, const ::Wartosc* /*request*/, ::Wartosc* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedzwieksz(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Wartosc,::Wartosc>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_zmniejsz : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_zmniejsz() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Wartosc, ::Wartosc>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Wartosc, ::Wartosc>* streamer) {
                       return this->Streamedzmniejsz(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_zmniejsz() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status zmniejsz(::grpc::ServerContext* /*context*/, const ::Wartosc* /*request*/, ::Wartosc* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedzmniejsz(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Wartosc,::Wartosc>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_zwieksz<WithStreamedUnaryMethod_zmniejsz<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_zwieksz<WithStreamedUnaryMethod_zmniejsz<Service > > StreamedService;
};


#endif  // GRPC_licznik_2eproto__INCLUDED
